version: "3.8"

services:
  mqtt-client:
    image: eclipse-mosquitto:2
    container_name: smartHome-mqtt
    ports:
      - "1885:1883"
    env_file:
      - .env
    volumes:
      - ./mqtt-config.json:/config/mqtt-config.json
