name: Generate IoT Configuration Artifact

on:
  push:
    branches:
      - main

jobs:
  generate-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Display config used by pipeline
        run: cat configs/config.yaml

      - name: Launch CI pipeline
        run: python pipeline.py

      - name: Upload generated artifact
        uses: actions/upload-artifact@v4
        with:
          name: iot-generated-configuration
          path: artifacts/*.zip